<?php include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml'; ?>
<?php use App\Core\View; ?>

<a href="<?php echo 'add'; ?>">Add New Book |</a>
<a href="<?php echo 'borrow'; ?>">Borrow Book |</a>
<a href="<?php echo 'getMyBooks'; ?>">My Books</a>


<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">ISBN</th>
            <th scope="col">Title</th>
            <th scope="col">Year</th>
            <th scope="col">Author</th>
            <th scope="col">Cover</th>
            <th scope="col">Created Date</th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($data as $book) { ?>
        <tr>
            <td><?php if (isset($book['isbn'])) echo View::escapeHTML($book['isbn']); ?></td>
            <td><?php if (isset($book['title'])) echo View::escapeHTML($book['title']); ?></td>
            <td><?php if (isset($book['year'])) echo View::escapeHTML($book['year']); ?></td>
            <td><?php if (isset($book['author'])) echo View::escapeHTML($book['author']); ?></td>
            <td><img style="width: 150px; height: 120px;" src="<?php echo '../uploads/' . $book['cover']; ?>"</td>
            <td><?php if (isset($book['createdDate'])) echo View::escapeHTML($book['createdDate']); ?></td>

            <td><a href="edit?isbn=<?php echo $book['isbn']; ?>">Edit</a></td>
            <td><a href="delete?isbn=<?php echo $book['isbn']; ?>">Delete</a></td>

        </tr>
        <?php
    }
    ?>
    </tbody>
</table>

<?php include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml'; ?>


