<div class="container">
    <h3>Add new User</h3>
    <form method="post" action="" class="form" enctype="multipart/form-data">
        <div class="group">
            <label for="firstname">Firstname</label>
            <input type="text" name="firstname" id="firstname">
        </div>
        <div class="group">
            <label for="lastname">Lastname</label>
            <input type="text" name="lastname" id="lastname">
        </div>
        <div class="group">
            <label for="email">Email</label>
            <input type="text" name="email" id="email">
        </div>
        <div class="group">
            <label for="phoneNumber">Phone Number</label>
            <input type="number" name="phoneNumber" id="phoneNumber">
        </div>
        <div class="group">
            <label for="address">Address</label>
            <input type="text" name="address" id="address">
        </div>
        <div class="group">
            <label for="gender">Gender</label>
            <input type="text" name="gender" id="gender">
        </div>
        <div class="group">
            <label for="avatar">Avatar</label>
            <input type="file" name="avatar" id="avatar">
        </div>
        <div class="group">
            <label for="registrationDate">Registration Date</label>
            <input type="date" name="registrationDate" id="registrationDate">
        </div>
        <div class="group">
            <label for="activeUntil">Active Until</label>
            <input type="date" name="activeUntil" id="activeUntil">
        </div>
        <div class="group">
            <input type="submit" value="Add">
        </div>
    </form>
</div>