<div class="container">
    <h3>Login</h3>
    <form method="post" action="" class="form" enctype="multipart/form-data">

        <div class="form-group">
            <label for="email">Email: </label>
            <input type="text" name="email" id="email" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for>Password: </label>
            <input type="password" name="passwrod" id="password" placeholder="Enter password">
        </div>
        <div class="group">
            <input type="submit" value="login">
        </div>
        <div class="question">Doesn't have an account? Please <a href="register">Register!</a></div>
    </form>
