<?php include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'header.phtml'; ?>
<?php use App\Core\View; ?>
<p>List of users and borrowed books: </p>
<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">ISBN</th>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Year</th>
        <th scope="col">Firstname</th>
        <th scope="col">Lastname</th>
    </tr>
    </thead>
    <tbody>
    <?php
    if (is_array($data) || is_object($data)) {
        foreach ($data as $borrowers)  { ?>
            <tr>
                <td><?php if(isset($borrowers['isbn'])) echo $borrowers['isbn']; ?></td>
                <td><?php if(isset($borrowers['title'])) echo $borrowers['title']; ?></td>
                <td><?php if(isset($borrowers['author'])) echo $borrowers['author']; ?></td>
                <td><?php if(isset($borrowers['year'])) echo $borrowers['year']; ?></td>
                <td><?php if(isset($borrowers['firstname'])) echo $borrowers['firstname']; ?></td>
                <td><?php if(isset($borrowers['lastname'])) echo $borrowers['lastname']; ?></td>
            </tr>
            <?php
        }
    }
    ?>
    </tbody>
</table>

<?php include dirname(__DIR__) . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'footer.phtml'; ?>