<!doctype html>
<html lang="en">
<head>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>
        Library
    </title>
</head>
<body>

    <div class="container">
        <h1>Library</h1>
        <p><q>Every book you see here has been somebody's best friend.</q> -Carlos Ruiz Zafon</p>
        <?php include 'navbar.phtml'; ?>
    </div>
</body>
</html>